
server:
  port: 5000

spring:
  profiles:
    active: default

a: 7
b: 3
---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 7070

a: 5
b: 12

---

spring:
  config:
    activate:
      on-profile: test

server:
  port: 4000

a: 8
b: 14